export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>
        <h1>몫대로</h1>
      </header>
      <body>{children}</body>
    </html>
  );
}
